[package]
name = "analytic"
version = "0.1.4"
authors = ["Aaron"]
edition = "2018"
license = "Apache-2.0"
description = "A math library"
repository = "https://github.com/Rustinante/analytic"

[dependencies]
num = "0.2"
rand = "0.6.5"
